import Footer from '@/components/shared/Footer/Footer'
import NavItem from '@/components/shared/Navbar/Navnar'
import { Roboto } from 'next/font/google'
import './assets/globals.css'

const roboto = Roboto({
  weight: ['300', '400', '500', '700', '900'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Nethlix | Open source IMDB Cheap Copy.',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NavItem />
        {children}
        <Footer />
      </body>
    </html>
  )
}
